In [3]:
import numpy as np

In [6]:
#브로드캐스팅 : 다른 크기의 배열간 연산
#(리스트에서는 먹히지 않음. 넘파이 사용)

#규칙 1. 두 배열의 차원수가 다른 경우 -> 더 작은 차원의 배열에 차원을 추가
#3 -> 1*3
#규칙 2. 두 배열 형상이 특정 차원에서 일치하지 않은 경우 -> 해당 차원 형상이 1인 배열을 다른 배열 형상과 일치하도록 증가
#1*3 -> 3*3
#임의의 차원에서 크기가 일치하지 않고 1도 아닌 경우 -> 적용 불가능

a = np.arange(3) #1차원 배열
print(a)

a = a[:, np.newaxis] #2차원 배열로 바꾸기
print(a)

b = np.arange(3)
print(b)

print(a+b) #조건이 맞으면 알아서 3by3으로 바뀌어 계산

[0 1 2]
[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [49]:
a = np.ones((2,3)) 
print(a)
b = np.arange(3) #1차원 벡터
print(b)

print(a+b)


[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [16]:
#배열에 대한 비교연산 -> 부울배열(또는 마스크) 출력
x = np.array([1, 2, 3, 4, 5])
print(x < 3)
print(x != 3)

[ True  True False False False]
[ True  True False  True  True]


In [26]:
np.random.seed(0)
a = np.random.randint(10, size=(3,4))
print(a)

np.count_nonzero(a < 6) #TRUE를 만족하는 원소의 갯수? 
#print(np.sum(a<6))도 같음

print(np.any(a > 8)) #a의 원소 중에 8보다 큰 원소가 하나라도 있는지? 
print(np.all(a > 1)) #a의 모든 원소가 1보다 큰지?

#마스킹 연산 수행 : 부울 배열을 마스크로 사용하여 True를 만족하는 값들을 선택
print(a[a<5]) #a의 원소 중 5보다 작은 원소들만 구성해 1차원 배열로 부분집합 형성
#데이터 분석 측면에서 많이 사용. 중요.



[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
True
False
[0 3 3 3 2 4]


In [35]:
#팬시 인덱싱 : 인덱스 배열을 이용한 배열 원소 접근
#한 번에 여러 배열 원소에 접근하는 방법. 인덱스 배열을 출력
np.random.seed(1)
x = np.random.randint(100, size=10)
print(x)

#70대 정수 값 선택하기#

a = x[2]; b = x[4]; c = x[6];
print([a, b, c])

#펜시 인덱셍 빙법
ind = [2, 4, 6]
print(x[ind])

[37 12 72  9 75  5 79 64 16  1]
[72, 75, 79]
[72 75 79]


In [36]:
#다차원 배열에 대한 팬시 인덱싱
np.random.seed(2)
x = np.random.randint(10, size=(3,5))
print(x)

row = [0, 1, 2]
col = [2, 1, 4]
x[row, col] #(0,2), (1,1), (2,4) #일차원 배열 출력

[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]]


array([6, 2, 6])

In [42]:
#다차원 배열에 대한 팬시 인덱싱 + 브로드 캐스팅 = 다차원 배열
np.random.seed(2)
x = np.random.randint(10, size=(3,5))
print(x)

row = np.array([0, 1, 2])
col = np.array([2, 1, 4])
print(x[row[:, np.newaxis], col])

[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]]
[[6 8 8]
 [1 2 4]
 [7 5 6]]
[11  9 10]


In [44]:
x = np.arange(1,13).reshape(3,4)
print(x)

#기본 인덱싱 + 팬시 인덱싱
print(x[2, [2, 0, 1]])

#슬라이싱 + 팬시 인덱싱
print(x[1:, [2, 0, 1]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[11  9 10]
[[ 7  5  6]
 [11  9 10]]
