In [2]:
import numpy as np

In [3]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

In [13]:
test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores)

jeremy_test_2 = student_scores[1, 3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([student_scores[0,1], student_scores[0,2]])
print(manual_adwoa_test_1)

cody = (student_scores[:,4]) #4대신 -1도 가능
print(cody)

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
93
[94 88]
[87 91 94]


In [17]:
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

selected = a[a > 5] #자주 쓰임
print(selected)

selected = a[(a > 5) | (a < 4)] #괄호 중요
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]


In [22]:
#실습 문제: 골디락스 포리지(죽) 페스티벌

porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge < 60]
print(cold)

hot = porridge[porridge > 80]
print(hot)

just_right = porridge[(porridge >= 60) & (porridge <= 80)]
print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]
