In [2]:
import numpy as np

In [6]:
np.random.seed(1)
arr = np.random.randint(10, size=(6,8))
print(arr)

print(arr[:2, :3]) #[행의start:stop:step, 열의start:stop:step]
print(arr[:3, ::2])

[[5 8 9 5 0 0 1 7]
 [6 9 2 4 5 2 4 2]
 [4 7 7 9 1 7 0 6]
 [9 9 7 6 9 1 0 1]
 [8 8 3 9 8 7 3 6]
 [5 1 9 3 4 8 1 4]]
[[5 8 9]
 [6 9 2]]
[[5 9 0 1]
 [6 2 5 4]
 [4 7 1 0]]


In [15]:
#배열 슬라이스 값을 변경하면 원본 배열 값도 변경된(!!!!리스트는 x!!!!)

arr_sub = arr[:2, :2]
print(arr_sub)

arr_sub[0,0] = 99 #배열 슬라이스 값 변경
print(arr) #원본 배열 값이 변경됨
print('\n')

#복사본으로 만드려면 .copy()사용
arr_sup2 = arr[:2, :2].copy()
print(arr_sup2)
arr_sup2[0,0] = 100 
print(arr_sup2)
print(arr) #원본은 변하지 않음

[[99  8]
 [ 6  9]]
[[99  8  9  5  0  0  1  7]
 [ 6  9  2  4  5  2  4  2]
 [ 4  7  7  9  1  7  0  6]
 [ 9  9  7  6  9  1  0  1]
 [ 8  8  3  9  8  7  3  6]
 [ 5  1  9  3  4  8  1  4]]


[[99  8]
 [ 6  9]]
[[100   8]
 [  6   9]]
[[99  8  9  5  0  0  1  7]
 [ 6  9  2  4  5  2  4  2]
 [ 4  7  7  9  1  7  0  6]
 [ 9  9  7  6  9  1  0  1]
 [ 8  8  3  9  8  7  3  6]
 [ 5  1  9  3  4  8  1  4]]


In [17]:
#배열 형성 메소드 arr.reshape()

arr = np.array([1,2,3,4,5,6,7,8,9]) #벡터
grid = arr.reshape(3, 3) #변경 전/후의 배열 크기가 동일해야 함
print(grid) #3*3배열로 바꾸기

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
#배열 결합
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array([7,8,9])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)

#np.vstack() 종방향으로 배열 연결
#np.hstack() 횡방향으로 배열 연결
arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)
print('\n')

print(np.hstack([arr_total, arr_total]))
print('\n')
print(np.concatenate([arr_total, arr_total]))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
#np.split(), np.vsplit(), np.hsplit(): 배열 분할 메소드
arr = np.array([1,2,3,99,99,3,2,1])
arr_1, arr_2, arr_3 = np.split(arr, [3, 5])
print(arr_1)
print(arr_2)
print(arr_3)

[1 2 3]
[99 99]
[3 2 1]
