In [11]:
import numpy as np

In [13]:
#numpy함수의 유니버셜 연산 

np.random.seed(1)
arr1 = np.random.randint(10, size=(5))
arr2 = np.random.randint(10, size=(5))
print(arr1, arr2)

arr1 = arr1 - 2 #배열과 스칼라의 연산
print(arr1)

arr3 = arr1 + arr2
print(arr3) #배열과 배열의 연산

arr4 = np.random.randint(10, size=(3,5))
print(arr4)

arr5 = arr4 ** 2 #다차원 배열의 연산
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [29]:
#유니버셜 함수들 
#np.abs() :절대값 함수
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j, 4-3j, 2+0j, 0+1j]) #복수수의 절대값도 제공
print(np.abs(x))


#np.linspace(start, stop, num): 선형 간격의 벡터 생성
y = np.linspace(0, 100, 5) #0과 100 사이의 간격을 5개로 쪼갠다
print(y)

theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

#지수와 로그 연산 : np.exp() np.power() 와 np.log() np.log10()


#집계 함수 제공 : reduce() 배열을 특정 연산으로 축소, 결과가 스칼라 값.
x = np.arange(1, 5)

aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)


#accumulate() : 계산의 중간 결과들을 배열로 저장
x = np.arange(1, 5)
print(x)

accum = np.add.accumulate(x)
print(accum)

accum = np.multiply.accumulate(x)
print(accum)

[2 1 0 1 2]
[5. 5. 2. 1.]
[  0.  25.  50.  75. 100.]
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
10
24
[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


54.63174026883457

In [31]:
#배열 합계 계산: np.sum() 파이썬 내장함수 sum()보다 훨씬 빠름
arr = np.random.rand(100) # rand() : create 0~1 real values 
np.sum(arr)

#np.max() np.min() np.median() np.mean() 괄호 안에 배열 이름  
#np.argmax()최대값의 인덱스 값 
#np.argmin()최솟값의 인덱스 값
#np.percentile() 하위 %의 원소 np.percentile(x, 25)하면 배열 x의 하위 25%값 출력
#np.any(arr>1) #배열원소 중 하나라도 1보다 큰 지
#np.all(arr>0) #배열원소 모두 0보다 큰 지 

#다차원 집계 : axis 속성
np.random.seed(5)
arr = np.random.randint(10, size=(3,4))
print(arr)

print(np.sum(arr, axis = 0)) #세로방향으로 집계, 열별로
print(np.sum(arr, axis = 1)) #가로방향으로 집계, 행별로

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]


array([15, 28,  8])